### PR TITLE
Add compilers section

### PR DESCRIPTION
**Pull request by Sparrow0hawk**
Updated the compiler section of software:

TODO:
- [ ] Spelling and style check
- [x] check i've got all compiler category modules from both ARC4 and ARC3
- [x] Updated `anaconda.md` to include `.conda` location guidance
- [x] Add general information to `start.md`

### CODE REVIEW

**Review by jhodrien — COMMENTED** [review]
Anaconda.  Does telling it to install a prefix still give you disk space bother?  I had an inkling it dropped all your packages into a shared directory before deploying them to the env dir.  I still have grumblings about what the right way to provide anaconda is, and the right way we should encourage users to use it.

Do we want a short page at the top level for compilers to explain what people are likely to find in that section?

**Comment by Sparrow0hawk** [comment]
I think you are right, conda by default downloads the compressed package and puts in in `.conda/pkgs` before it builds it and puts it into the environment (in `.conda/envs`). Using the prefix option doesn't change this it just allows you specify a non-default environment location. I kept it in from our previous page but I think it still would probably lead to disk space problems with the default `.conda` location still being `$HOME`.

I'll add a section about moving `.conda` to `/nobackup` as that is usually what I recommend users do.

**Comment by Sparrow0hawk** [comment]
Couple of updates:
- added an index to the `start.md` page
- removed the `conda install` with `-p/--prefix` and included a section on moving and symlinking `.conda` to `/nobackup` 
- Added `software/applications/dlpoly/license.md` into the _toc

**Comment by jhodrien** [comment]
Don't mind whether we have the full list there or not (given the list is also available on the left side), but if we do have it, can we make sure the application names line up?  There's a few things like AMBER on the left, but Amber on that page.  Should probably be Amber.  MATLAB vs Matlab (should be MATLAB).

**Pull request merged**
