### PR TITLE
Updates to reflect newer version of mobaXTerm

### PR DESCRIPTION
**Pull request by NGRhodes**
Just a few minor updates (2 images and 1 line of text) on getting_started/logon.html
Also added experimental evnironment config for windows.

### CODE REVIEW

**Review by Sparrow0hawk — CHANGES_REQUESTED** [review]
Just for 100% consistency (and I realise actually an earlier screen grab isn't consistent) could you do the screengrabs with the username set to `medacola` just so that the username renames the same throughout and avoids confusion.

**Comment by NGRhodes** [comment]
@Sparrow0hawk - images updated

**Review by Sparrow0hawk — APPROVED** [review]
Perfect, thanks @NGRhodes!

**Comment by Sparrow0hawk** [comment]
@NGRhodes happy for you to merge this when ready

**Pull request merged**
