### PR TITLE
updated instructions about using mobaXterm terminal

### PR DESCRIPTION
**Pull request by Sparrow0hawk**

### CODE REVIEW

**Review by jhodrien — COMMENTED** [review]
Add User USERNAME to the remote-access section of the ssh config, and it's a yes from me.

**Comment by NGRhodes** [comment]
I think the warning wants to be at the top of the MobaXterm section as it applies equally to using a session and terminal within MobaXterm.

**Review by NGRhodes — CHANGES_REQUESTED** [review]
I think the warning wants to be at the top of the "Connecting via MobaXTerm" section as it applies equally to using a session and terminal within MobaXTerm.

**Comment by Sparrow0hawk** [comment]
Addressed @NGRhodes suggestion in 74ea672

@jhodrien suggestion is potentially redundant due to setting `User USERNAME` in earlier host rule.

**Review by jhodrien — APPROVED** [review]

**Review by NGRhodes — APPROVED** [review]

**Pull request merged**
